#!/bin/bash
# Quick Cheat Sheet - Copy & Paste Commands

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          PV Lakehouse - Quick Command Reference             ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

echo "📦 BRONZE LAYER - Data Ingestion"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "bash src/pv_lakehouse/etl/scripts/spark-submit.sh src/pv_lakehouse/etl/bronze/load_facilities.py --mode incremental"
echo "bash src/pv_lakehouse/etl/scripts/spark-submit.sh src/pv_lakehouse/etl/bronze/load_facility_timeseries.py --mode incremental"
echo "bash src/pv_lakehouse/etl/scripts/spark-submit.sh src/pv_lakehouse/etl/bronze/load_facility_weather.py --mode incremental"
echo "bash src/pv_lakehouse/etl/scripts/spark-submit.sh src/pv_lakehouse/etl/bronze/load_facility_air_quality.py --mode incremental"
echo ""

echo "✨ SILVER LAYER - Data Transformation"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "bash src/pv_lakehouse/etl/scripts/spark-submit.sh src/pv_lakehouse/etl/silver/cli.py facility_master --mode full"
echo "bash src/pv_lakehouse/etl/scripts/spark-submit.sh src/pv_lakehouse/etl/silver/cli.py hourly_energy --mode full"
echo "bash src/pv_lakehouse/etl/scripts/spark-submit.sh src/pv_lakehouse/etl/silver/cli.py hourly_weather --mode full"
echo "bash src/pv_lakehouse/etl/scripts/spark-submit.sh src/pv_lakehouse/etl/silver/cli.py hourly_air_quality --mode full"
echo ""

echo "🔄 BACKFILL - Load Historical Data"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Bronze Backfill (NOTE: Timeseries uses UTC time, auto-converts to Brisbane timezone)"
echo "bash src/pv_lakehouse/etl/scripts/spark-submit.sh src/pv_lakehouse/etl/bronze/load_facility_timeseries.py --mode backfill --date-start 2025-10-01T00:00:00 --date-end 2025-10-22T23:59:59"
echo "bash src/pv_lakehouse/etl/scripts/spark-submit.sh src/pv_lakehouse/etl/bronze/load_facility_weather.py --mode backfill --start 2025-10-01 --end 2025-10-22"
echo "bash src/pv_lakehouse/etl/scripts/spark-submit.sh src/pv_lakehouse/etl/bronze/load_facility_air_quality.py --mode backfill --start 2025-10-01 --end 2025-10-22"
echo ""
echo "# Silver Transform (Full mode processes all Bronze data)"
echo "bash src/pv_lakehouse/etl/scripts/spark-submit.sh src/pv_lakehouse/etl/silver/cli.py hourly_energy --mode full"
echo "bash src/pv_lakehouse/etl/scripts/spark-submit.sh src/pv_lakehouse/etl/silver/cli.py hourly_weather --mode full"
echo "bash src/pv_lakehouse/etl/scripts/spark-submit.sh src/pv_lakehouse/etl/silver/cli.py hourly_air_quality --mode full"
echo ""

echo "🗑️  DELETE DATA - Cleanup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "docker compose -f docker/docker-compose.yml exec trino trino --catalog iceberg --schema lh --execute \"DELETE FROM bronze.raw_facility_timeseries;\""
echo "docker compose -f docker/docker-compose.yml exec trino trino --catalog iceberg --schema lh --execute \"DELETE FROM bronze.raw_facility_weather;\""
echo "docker compose -f docker/docker-compose.yml exec trino trino --catalog iceberg --schema lh --execute \"DELETE FROM bronze.raw_facility_air_quality;\""
echo ""

echo "📊 QUERY DATA - Check Results"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Count rows"
echo "docker compose -f docker/docker-compose.yml exec trino trino --catalog iceberg --schema lh --execute \"SELECT COUNT(*) FROM bronze.raw_facility_timeseries;\""
echo ""
echo "# Check date ranges"
echo "docker compose -f docker/docker-compose.yml exec trino trino --catalog iceberg --schema lh --execute \\"
echo "  \"SELECT MIN(interval_ts), MAX(interval_ts), COUNT(*) FROM bronze.raw_facility_timeseries;\""
echo ""

echo "🐳 DOCKER - Service Management"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "docker compose -f docker/docker-compose.yml up -d"
echo "docker compose -f docker/docker-compose.yml ps"
echo "docker compose -f docker/docker-compose.yml logs -f spark-master"
echo "docker compose -f docker/docker-compose.yml exec spark-master bash"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚡ TIMEZONE NOTE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "• Timeseries: Input UTC datetime (auto-converts to Brisbane UTC+10 for API)"
echo "• Weather/Air Quality: Input date only (API uses UTC timezone)"
echo "• Example: --date-start 2025-10-01T00:00:00 → Data starts exactly at 2025-10-01 00:00 UTC"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💡 Tip: All scripts in src/pv_lakehouse/etl/scripts/"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
